#!/usr/bin/env python3
"""Run M0-M4 cuRobo collision-world experiments over a seed range."""

from __future__ import annotations

import argparse
import contextlib
import gc
import json
import os
import shlex
import subprocess
import sys
import time
import traceback
from pathlib import Path
from typing import Any, Callable, Iterable

import numpy as np

from maniskill_curobo_real.scene_builder import (
    build_mask_exclusion_scene,
    build_oracle_instance_cuboid_scene,
    build_oracle_instance_mesh_scene,
    build_oracle_instance_obb_scene,
    build_oracle_instance_voxel_esdf_scene,
    build_static_table_scene,
    build_zerograsp_instance_cuboid_scene,
    build_zerograsp_instance_mesh_scene,
    build_zerograsp_instance_obb_scene,
    build_zerograsp_instance_voxel_esdf_scene,
    write_scene_result,
    write_voxel_scene_result,
)


DEFAULT_MANISKILL_PYTHON = Path("maniskill_curobo/envs/maniskill_curobo/bin/python")
DEFAULT_ZEROGRASP_PYTHON = Path("/home/openclaw-server/miniconda3/envs/graduate/bin/python")
DEFAULT_CANDIDATE_ROOT = Path("maniskill_curobo/runs/depth_corrected_settle20_seed1_200_rerun")
DEFAULT_CAMERA_EYE = (-0.20, 0.0, 0.27)
DEFAULT_CAMERA_TARGET = (0.05, 0.0, 0.08)
STAGES = ("m0", "m1", "m2", "m3", "m4a", "m4b", "m4c")
STAGE_LABELS = {
    "m0": "m0_maniskill_truth",
    "m1": "m1_static_table",
    "m2": "m2_mask_exclusion_table",
    "m3": "m3_oracle_instance_cuboids",
    "m4a": "m4a_oracle_instance_yaw_obb",
    "m4b": "m4b_oracle_instance_convex_mesh",
    "m4c": "m4c_oracle_instance_voxel_esdf",
}
ZEROGRASP_RECONSTRUCTION_STAGE_LABELS = {
    "m3": "m3_zerograsp_reconstruction_cuboids",
    "m4a": "m4a_zerograsp_reconstruction_yaw_obb",
    "m4b": "m4b_zerograsp_reconstruction_convex_mesh",
    "m4c": "m4c_zerograsp_reconstruction_voxel_esdf",
}


def stage_labels_for(args: argparse.Namespace) -> dict[str, str]:
    if args.point_cloud_source == "zerograsp_reconstruction":
        return ZEROGRASP_RECONSTRUCTION_STAGE_LABELS
    return STAGE_LABELS


def stage_label_for(args: argparse.Namespace, stage: str) -> str:
    return stage_labels_for(args)[stage]


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--env-id", default="PickSingleYCB-v1")
    parser.add_argument("--seed-start", type=int, default=1)
    parser.add_argument("--seed-end", type=int, default=200)
    parser.add_argument(
        "--stages",
        nargs="+",
        choices=STAGES,
        default=list(STAGES),
        help="Collision-world stages to run.",
    )
    parser.add_argument(
        "--output-root",
        default="maniskill_curobo_real/runs/world_collision_m0_m3_seed1_200",
    )
    parser.add_argument(
        "--reuse-candidate-root",
        default=str(DEFAULT_CANDIDATE_ROOT),
        help="Existing root with seedNNN/setup/zg_output generated by ZeroGrasp.",
    )
    parser.add_argument(
        "--point-cloud-source",
        choices=("maniskill_depth", "zerograsp_reconstruction"),
        default="maniskill_depth",
        help="Geometry source for M3/M4 stages.",
    )
    parser.add_argument(
        "--zerograsp-reconstruction-root",
        default=None,
        help=(
            "Root containing seedNNN/setup/zg_input and zg_output generated "
            "with the all-objects mask."
        ),
    )
    parser.add_argument("--reuse-existing", action="store_true")
    parser.add_argument("--camera", default="base_camera")
    parser.add_argument("--width", type=int, default=1280)
    parser.add_argument("--height", type=int, default=1024)
    parser.add_argument("--render-width", type=int, default=1280)
    parser.add_argument("--render-height", type=int, default=1024)
    parser.add_argument("--camera-eye", type=float, nargs=3, default=list(DEFAULT_CAMERA_EYE))
    parser.add_argument("--camera-target", type=float, nargs=3, default=list(DEFAULT_CAMERA_TARGET))
    parser.add_argument("--mask-mode", default="task-target")
    parser.add_argument("--approach-axis", default="positive-x")
    parser.add_argument("--grasp-depth-scale", type=float, default=1.0)
    parser.add_argument("--grasp-depth-max-offset", type=float, default=0.04)
    parser.add_argument("--grasp-depth-auto-fallback", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--candidate-top-k", type=int, default=20)
    parser.add_argument("--pregrasp-offset", type=float, default=0.10)
    parser.add_argument("--lift-offset", type=float, default=0.15)
    parser.add_argument("--workspace-z-min", type=float, default=0.01)
    parser.add_argument("--close-steps", type=int, default=20)
    parser.add_argument("--settle-steps", type=int, default=50)
    parser.add_argument("--settle-before-export-steps", type=int, default=20)
    parser.add_argument("--action-repeat", type=int, default=2)
    parser.add_argument("--max-waypoints-per-stage", type=int, default=80)
    parser.add_argument("--robot-config", default="franka.yml")
    parser.add_argument("--scene-min-cuboid-dimension", type=float, default=0.005)
    parser.add_argument(
        "--m3-instance-padding",
        type=float,
        default=0.0,
        help=(
            "Padding for M3 oracle instance cuboids. Default 0.0 uses the "
            "raw per-instance AABB; negative values shrink it."
        ),
    )
    parser.add_argument("--m3-min-instance-points", type=int, default=400)
    parser.add_argument("--m3-max-obstacles", type=int, default=50)
    parser.add_argument("--m3-debug-views", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--m3-debug-max-points", type=int, default=60000)
    parser.add_argument("--m4-instance-padding", type=float, default=0.0)
    parser.add_argument("--m4-min-instance-points", type=int, default=400)
    parser.add_argument("--m4-max-obstacles", type=int, default=50)
    parser.add_argument("--m4-mesh-max-points", type=int, default=2500)
    parser.add_argument("--m4-voxel-max-points", type=int, default=1500)
    parser.add_argument("--m4-voxel-size", type=float, default=0.01)
    parser.add_argument("--m4-voxel-dilation", type=int, default=0)
    parser.add_argument(
        "--persistent-execution",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Run execute_curobo_pick in-process and reuse the ManiSkill env. "
            "cuRobo planner is reused only when the scene is unchanged."
        ),
    )
    parser.add_argument("--warmup-iterations", type=int, default=2)
    parser.add_argument("--video-fps", type=int, default=20)
    parser.add_argument("--record-video", action="store_true")
    parser.add_argument("--maniskill-python", default=str(DEFAULT_MANISKILL_PYTHON))
    parser.add_argument("--zerograsp-python", default=str(DEFAULT_ZEROGRASP_PYTHON))
    parser.add_argument(
        "--checkpoint",
        default="checkpoints/zerograsp_cvpr2025/zerograsp_demo.ckpt",
    )
    parser.add_argument("--config", default="configs/maniskill.yaml")
    parser.add_argument(
        "--generate-missing-candidates",
        action="store_true",
        help=(
            "If --reuse-candidate-root does not contain a seed candidate, export "
            "RGB-D/mask and run ZeroGrasp under output_root/candidates."
        ),
    )
    return parser.parse_args(argv)


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv)
    if args.point_cloud_source == "zerograsp_reconstruction":
        unsupported = sorted(set(args.stages) - {"m3", "m4a", "m4b", "m4c"})
        if unsupported:
            raise ValueError(
                "ZeroGrasp reconstruction experiments start at M3; unsupported "
                f"stages: {unsupported}"
            )
        if not args.zerograsp_reconstruction_root:
            raise ValueError(
                "--zerograsp-reconstruction-root is required for "
                "--point-cloud-source zerograsp_reconstruction."
            )
    if "m4c" in args.stages and not args.persistent_execution:
        raise ValueError("M4-C native VoxelGrid requires --persistent-execution.")
    output_root = Path(args.output_root).expanduser().resolve()
    output_root.mkdir(parents=True, exist_ok=True)
    candidate_root = Path(args.reuse_candidate_root).expanduser().resolve()
    seeds = list(range(int(args.seed_start), int(args.seed_end) + 1))
    records_by_stage = load_existing_records(output_root) if args.reuse_existing else {}
    execution_runner = (
        PersistentRealExecutionRunner(repo_root=Path(__file__).resolve().parents[1])
        if args.persistent_execution
        else None
    )

    try:
        for stage in args.stages:
            stage_label = stage_label_for(args, stage)
            print(f"=== {stage_label} seeds {seeds[0]}-{seeds[-1]} ===", flush=True)
            stage_records = records_by_stage.setdefault(stage, {})
            if stage == "m1":
                write_global_m1_scene(output_root / stage_label / "scene")
            for index, seed in enumerate(seeds, start=1):
                print(f"[{stage_label}] seed {seed} ({index}/{len(seeds)})", flush=True)
                existing = stage_records.get(seed)
                record = run_stage_seed(
                    args=args,
                    stage=stage,
                    output_root=output_root,
                    candidate_root=candidate_root,
                    seed=seed,
                    existing=existing,
                    execution_runner=execution_runner,
                )
                stage_records[seed] = record
                write_results(output_root, args, seeds, records_by_stage)
                print(
                    f"  status={record.get('status')} outcome={record.get('outcome')} "
                    f"lift={record.get('object_lift_success')}",
                    flush=True,
                )
    finally:
        if execution_runner is not None:
            execution_runner.close()

    summary = write_results(output_root, args, seeds, records_by_stage)
    print(json.dumps(summary["counts"], ensure_ascii=False, indent=2), flush=True)
    return 0


def run_stage_seed(
    *,
    args: argparse.Namespace,
    stage: str,
    output_root: Path,
    candidate_root: Path,
    seed: int,
    existing: dict[str, Any] | None,
    execution_runner: "PersistentRealExecutionRunner | None" = None,
) -> dict[str, Any]:
    run_started = time.time()
    stage_label = stage_label_for(args, stage)
    run_dir = output_root / stage_label / f"seed{seed:03d}"
    manifest_path = run_dir / "run_manifest.json"
    if args.reuse_existing and manifest_path.is_file():
        return summarize_run(stage=stage, seed=seed, run_dir=run_dir, reused=True)

    zg_output_dir = find_candidate_output(candidate_root, seed)
    if zg_output_dir is None and args.generate_missing_candidates:
        zg_output_dir = generate_candidate_for_seed(
            args=args,
            seed=seed,
            candidate_dir=output_root / "candidates" / f"seed{seed:03d}" / "setup",
        )
    if zg_output_dir is None:
        return {
            "stage": stage,
            "seed": seed,
            "status": "missing_zerograsp_candidate",
            "candidate_root": str(candidate_root),
        }

    scene_model: Path | None = None
    scene_source = "maniskill"
    scene_build: dict[str, Any] | None = None
    if stage == "m1":
        scene_source = "fixed"
        scene_model = output_root / stage_label / "scene" / "curobo_scene.yml"
    elif stage in {"m2", "m3", "m4a", "m4b", "m4c"}:
        scene_source = "fixed"
        scene_name = "curobo_scene_voxel.npz" if stage == "m4c" else "curobo_scene.yml"
        scene_model = run_dir / "real_scene" / scene_name
        scene_env = execution_runner.acquire_env(args) if execution_runner is not None else None
        scene_build = build_depth_scene_for_seed(
            args=args,
            seed=seed,
            stage=stage,
            scene_path=scene_model,
            env=scene_env,
        )

    command = execute_command(
        args=args,
        seed=seed,
        zg_output_dir=zg_output_dir,
        run_dir=run_dir,
        scene_source=scene_source,
        scene_model=scene_model,
    )
    if execution_runner is None:
        result = run_command(
            command,
            cwd=Path(__file__).resolve().parents[1],
            logs_dir=run_dir / "logs",
            name="execute",
        )
    else:
        result = execution_runner.run(
            command,
            logs_dir=run_dir / "logs",
            name="execute",
        )
    summary = summarize_run(stage=stage, seed=seed, run_dir=run_dir, command=result)
    summary["scene_build"] = scene_build
    summary["total_runtime_sec"] = float(time.time() - run_started)
    return summary


def generate_candidate_for_seed(
    *,
    args: argparse.Namespace,
    seed: int,
    candidate_dir: Path,
) -> Path | None:
    input_dir = candidate_dir / "zg_input"
    output_dir = candidate_dir / "zg_output"
    logs_dir = candidate_dir / "logs"
    candidate_path = output_dir / "recommended_grasp_top1.json"
    if candidate_path.is_file():
        return output_dir

    export_result = run_command(
        export_command(args=args, seed=seed, input_dir=input_dir),
        cwd=Path(__file__).resolve().parents[1],
        logs_dir=logs_dir,
        name="export_input",
    )
    if export_result["exit_code"] != 0:
        return None
    zg_result = run_command(
        zerograsp_command(args=args, seed=seed, input_dir=input_dir, output_dir=output_dir),
        cwd=Path(__file__).resolve().parents[1],
        logs_dir=logs_dir,
        name="zerograsp",
    )
    if zg_result["exit_code"] != 0 or not candidate_path.is_file():
        return None
    return output_dir


def export_command(
    *,
    args: argparse.Namespace,
    seed: int,
    input_dir: Path,
) -> list[str]:
    return [
        str(Path(args.maniskill_python).expanduser()),
        "-m",
        "maniskill_codex.export_zerograsp_input",
        "--env-id",
        args.env_id,
        "--seed",
        str(seed),
        "--camera",
        args.camera,
        "--width",
        str(args.width),
        "--height",
        str(args.height),
        "--control-mode",
        "pd_joint_pos",
        "--settle-before-export-steps",
        str(args.settle_before_export_steps),
        "--camera-eye",
        *[str(float(value)) for value in args.camera_eye],
        "--camera-target",
        *[str(float(value)) for value in args.camera_target],
        "--mask-mode",
        args.mask_mode,
        "--output-dir",
        str(input_dir),
    ]


def zerograsp_command(
    *,
    args: argparse.Namespace,
    seed: int,
    input_dir: Path,
    output_dir: Path,
) -> list[str]:
    return [
        str(Path(args.zerograsp_python).expanduser()),
        "-m",
        "maniskill_codex.run_zerograsp_inference",
        "--img-path",
        str(input_dir / "rgb.png"),
        "--depth-path",
        str(input_dir / "depth.png"),
        "--mask-path",
        str(input_dir / "mask.png"),
        "--camera-info-path",
        str(input_dir / "camera.json"),
        "--output-dir",
        str(output_dir),
        "--checkpoint",
        args.checkpoint,
        "--config",
        args.config,
        "--random-seed",
        str(seed),
        "--enable-collision-detection",
    ]


def write_global_m1_scene(scene_dir: Path) -> None:
    write_scene_result(
        build_static_table_scene(source="m1_static_table_global"),
        scene_dir / "curobo_scene.yml",
        metadata_path=scene_dir / "curobo_scene_metadata.json",
    )


def build_depth_scene_for_seed(
    *,
    args: argparse.Namespace,
    seed: int,
    stage: str,
    scene_path: Path,
    env: Any | None = None,
) -> dict[str, Any]:
    build_started = time.time()
    from maniskill_codex.zerograsp_inputs import (
        collect_mask_actor_records,
        extract_zerograsp_input,
    )
    from maniskill_curobo.scripts import execute_curobo_pick as execute

    env_args = argparse.Namespace(
        env_id=args.env_id,
        seed=seed,
        camera=args.camera,
        width=args.width,
        height=args.height,
        render_width=args.render_width,
        render_height=args.render_height,
        camera_eye=args.camera_eye,
        camera_target=args.camera_target,
        gripper_open=1.0,
    )
    owns_env = env is None
    if env is None:
        env = build_real_benchmark_env(env_args)
    try:
        obs, _ = env.reset(seed=seed)
        if args.settle_before_export_steps > 0:
            obs, _ = execute.settle_environment(
                env,
                steps=int(args.settle_before_export_steps),
                gripper=1.0,
            )
        camera_model = execute.camera_model_matrix(env, args.camera)
        world_from_base = execute.robot_base_matrix(env)
        if args.point_cloud_source == "zerograsp_reconstruction":
            reconstruction_dirs = find_reconstruction_dirs(
                Path(args.zerograsp_reconstruction_root).expanduser().resolve(),
                seed,
            )
            if reconstruction_dirs is None:
                raise FileNotFoundError(
                    f"Missing ZeroGrasp reconstruction for seed={seed} under "
                    f"{args.zerograsp_reconstruction_root}"
                )
            input_dir, output_dir = reconstruction_dirs
            from maniskill_curobo_real.zerograsp_reconstruction import (
                load_zerograsp_reconstructed_instances,
            )

            instances = load_zerograsp_reconstructed_instances(
                input_dir=input_dir,
                output_dir=output_dir,
                camera_model_matrix=camera_model,
                world_from_base_matrix=world_from_base,
            )
            if stage == "m3":
                result = build_zerograsp_instance_cuboid_scene(
                    instances=instances,
                    min_instance_points=int(args.m3_min_instance_points),
                    instance_padding=float(args.m3_instance_padding),
                    min_cuboid_dimension=float(args.scene_min_cuboid_dimension),
                    max_obstacles=int(args.m3_max_obstacles),
                )
            elif stage == "m4a":
                result = build_zerograsp_instance_obb_scene(
                    instances=instances,
                    min_instance_points=int(args.m4_min_instance_points),
                    instance_padding=float(args.m4_instance_padding),
                    min_cuboid_dimension=float(args.scene_min_cuboid_dimension),
                    max_obstacles=int(args.m4_max_obstacles),
                )
            elif stage == "m4b":
                result = build_zerograsp_instance_mesh_scene(
                    instances=instances,
                    min_instance_points=int(args.m4_min_instance_points),
                    max_obstacles=int(args.m4_max_obstacles),
                    max_points_per_instance=int(args.m4_mesh_max_points),
                    fallback_padding=float(args.m4_instance_padding),
                    min_cuboid_dimension=float(args.scene_min_cuboid_dimension),
                )
            elif stage == "m4c":
                result = build_zerograsp_instance_voxel_esdf_scene(
                    instances=instances,
                    min_instance_points=int(args.m4_min_instance_points),
                    max_obstacles=int(args.m4_max_obstacles),
                    max_points_per_instance=int(args.m4_voxel_max_points),
                    voxel_size=float(args.m4_voxel_size),
                    dilation_voxels=int(args.m4_voxel_dilation),
                )
            else:
                raise ValueError(
                    f"ZeroGrasp reconstruction is unsupported for stage={stage!r}."
                )
            if args.m3_debug_views:
                write_zerograsp_debug_views(
                    output_dir=scene_path.parent / "debug_views",
                    input_dir=input_dir,
                    instances=instances,
                    camera_model=camera_model,
                    world_from_base=world_from_base,
                    min_instance_points=int(
                        args.m3_min_instance_points
                        if stage == "m3"
                        else args.m4_min_instance_points
                    ),
                    instance_padding=float(
                        args.m3_instance_padding
                        if stage == "m3"
                        else args.m4_instance_padding
                    ),
                    min_cuboid_dimension=float(args.scene_min_cuboid_dimension),
                    max_points=int(args.m3_debug_max_points),
                )
        else:
            bundle = extract_zerograsp_input(
                obs,
                env,
                args.camera,
                mask_mode=args.mask_mode,
            )
            if stage == "m2":
                result = build_mask_exclusion_scene(
                    depth_m=bundle.depth,
                    mask=bundle.mask,
                    camera_matrix=bundle.camera_matrix,
                    camera_model_matrix=camera_model,
                    world_from_base_matrix=world_from_base,
                )
            elif stage in {"m3", "m4a", "m4b", "m4c"}:
                segmentation = raw_segmentation(obs, args.camera)
                all_object_records = collect_mask_actor_records(env, "all-objects")
                target_records = collect_mask_actor_records(env, "task-target")
                common = {
                    "depth_m": bundle.depth,
                    "mask": bundle.mask,
                    "segmentation": segmentation,
                    "object_records": all_object_records,
                    "target_records": target_records,
                    "camera_matrix": bundle.camera_matrix,
                    "camera_model_matrix": camera_model,
                    "world_from_base_matrix": world_from_base,
                }
                if stage == "m3":
                    result = build_oracle_instance_cuboid_scene(
                        **common,
                        min_instance_points=int(args.m3_min_instance_points),
                        instance_padding=float(args.m3_instance_padding),
                        min_cuboid_dimension=float(args.scene_min_cuboid_dimension),
                        max_obstacles=int(args.m3_max_obstacles),
                    )
                elif stage == "m4a":
                    result = build_oracle_instance_obb_scene(
                        **common,
                        min_instance_points=int(args.m4_min_instance_points),
                        instance_padding=float(args.m4_instance_padding),
                        min_cuboid_dimension=float(args.scene_min_cuboid_dimension),
                        max_obstacles=int(args.m4_max_obstacles),
                    )
                elif stage == "m4b":
                    result = build_oracle_instance_mesh_scene(
                        **common,
                        min_instance_points=int(args.m4_min_instance_points),
                        max_obstacles=int(args.m4_max_obstacles),
                        max_points_per_instance=int(args.m4_mesh_max_points),
                        fallback_padding=float(args.m4_instance_padding),
                        min_cuboid_dimension=float(args.scene_min_cuboid_dimension),
                    )
                else:
                    result = build_oracle_instance_voxel_esdf_scene(
                        **common,
                        min_instance_points=int(args.m4_min_instance_points),
                        max_obstacles=int(args.m4_max_obstacles),
                        max_points_per_instance=int(args.m4_voxel_max_points),
                        voxel_size=float(args.m4_voxel_size),
                        dilation_voxels=int(args.m4_voxel_dilation),
                    )
                if args.m3_debug_views:
                    write_m3_debug_views(
                        output_dir=scene_path.parent / "debug_views",
                        bundle=bundle,
                        segmentation=segmentation,
                        object_records=all_object_records,
                        target_records=target_records,
                        camera_model=camera_model,
                        world_from_base=world_from_base,
                        min_instance_points=int(
                            args.m3_min_instance_points
                            if stage == "m3"
                            else args.m4_min_instance_points
                        ),
                        instance_padding=float(
                            args.m3_instance_padding
                            if stage == "m3"
                            else args.m4_instance_padding
                        ),
                        min_cuboid_dimension=float(args.scene_min_cuboid_dimension),
                        max_points=int(args.m3_debug_max_points),
                    )
            else:
                raise ValueError(f"Depth scene build is unsupported for stage={stage!r}.")
        valid_points = int(result.metadata.get("valid_points", 0))
        minimum_valid_points = (
            100
            if args.point_cloud_source == "zerograsp_reconstruction"
            else 1000
        )
        if valid_points < minimum_valid_points:
            raise RuntimeError(
                f"Invalid collision scene for seed={seed}, stage={stage}: "
                f"valid_points={valid_points}, required={minimum_valid_points}."
            )
        metadata_path = scene_path.with_name("curobo_scene_metadata.json")
        if stage == "m4c":
            write_voxel_scene_result(result, scene_path, metadata_path=metadata_path)
        else:
            write_scene_result(result, scene_path, metadata_path=metadata_path)
        return {
            "scene_model": str(scene_path),
            "metadata": str(metadata_path),
            "runtime_sec": float(time.time() - build_started),
            "summary": {
                "source": result.metadata.get("source"),
                "n_obstacles": result.metadata.get("n_obstacles"),
                "target_points": result.metadata.get("target_points"),
                "non_target_points": result.metadata.get("non_target_points"),
                "n_pointcloud_obstacles": result.metadata.get("n_pointcloud_obstacles"),
            },
        }
    finally:
        if owns_env:
            env.close()


def write_m3_debug_views(
    *,
    output_dir: Path,
    bundle: Any,
    segmentation: Any,
    object_records: list[dict[str, Any]],
    target_records: list[dict[str, Any]],
    camera_model: Any,
    world_from_base: Any,
    min_instance_points: int,
    instance_padding: float,
    min_cuboid_dimension: float,
    max_points: int,
) -> None:
    from maniskill_curobo_real.scene_builder import (
        DEFAULT_WORKSPACE_BOUNDS,
        rgbd_to_base_cloud,
        valid_workspace_mask,
    )
    from maniskill_curobo_real.visualize_m3_pointcloud import (
        save_input_images,
        visualize_oracle_instances,
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    save_input_images(output_dir, bundle.rgb, bundle.mask)
    cloud = rgbd_to_base_cloud(
        depth_m=bundle.depth,
        camera_matrix=bundle.camera_matrix,
        camera_model_matrix=camera_model,
        world_from_base_matrix=world_from_base,
    )
    valid = valid_workspace_mask(cloud, bundle.depth, DEFAULT_WORKSPACE_BOUNDS)
    visualize_oracle_instances(
        output_dir=output_dir / "oracle_instances",
        cloud=cloud,
        valid=valid,
        target_mask=bundle.mask.reshape(-1) > 0,
        segmentation=segmentation.reshape(-1),
        object_records=object_records,
        target_records=target_records,
        min_instance_points=int(min_instance_points),
        instance_padding=float(instance_padding),
        min_cuboid_dimension=float(min_cuboid_dimension),
        max_points=int(max_points),
        rgb=bundle.rgb,
        camera_matrix=bundle.camera_matrix,
        camera_model_matrix=camera_model,
        world_from_base_matrix=world_from_base,
    )


def write_zerograsp_debug_views(
    *,
    output_dir: Path,
    input_dir: Path,
    instances: list[Any],
    camera_model: Any,
    world_from_base: Any,
    min_instance_points: int,
    instance_padding: float,
    min_cuboid_dimension: float,
    max_points: int,
) -> None:
    from maniskill_curobo_real.visualize_m3_pointcloud import (
        save_input_images,
        visualize_oracle_instances,
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    with np.load(input_dir / "rgbd.npz") as payload:
        rgb = payload["rgb"]
        mask = payload["mask"]
        camera_matrix = payload["cam_K"]
    save_input_images(output_dir, rgb, mask)

    clouds = []
    segmentations = []
    target_flags = []
    object_records = []
    target_records = []
    for instance in instances:
        points = instance.points_base
        if points.shape[0] == 0:
            continue
        segmentation_id = (
            int(instance.segmentation_id)
            if instance.segmentation_id is not None
            else int(instance.label)
        )
        clouds.append(points)
        segmentations.append(
            np.full(points.shape[0], segmentation_id, dtype="int32")
        )
        target_flags.append(
            np.full(
                points.shape[0],
                bool(instance.is_task_target),
                dtype=bool,
            )
        )
        record = {
            "segmentation_id": segmentation_id,
            "actor_name": instance.actor_name,
        }
        object_records.append(record)
        if instance.is_task_target:
            target_records.append(record)
    if not clouds:
        return
    cloud = np.concatenate(clouds, axis=0)
    segmentation = np.concatenate(segmentations, axis=0)
    target_mask = np.concatenate(target_flags, axis=0)
    visualize_oracle_instances(
        output_dir=output_dir / "zerograsp_instances",
        cloud=cloud,
        valid=np.ones(cloud.shape[0], dtype=bool),
        target_mask=target_mask,
        segmentation=segmentation,
        object_records=object_records,
        target_records=target_records,
        min_instance_points=int(min_instance_points),
        instance_padding=float(instance_padding),
        min_cuboid_dimension=float(min_cuboid_dimension),
        max_points=int(max_points),
        rgb=rgb,
        camera_matrix=camera_matrix,
        camera_model_matrix=camera_model,
        world_from_base_matrix=world_from_base,
        title="ZeroGrasp reconstructed instance point clouds",
        overlay_title="ZeroGrasp reconstructions projected on RGB",
    )


def execute_command(
    *,
    args: argparse.Namespace,
    seed: int,
    zg_output_dir: Path,
    run_dir: Path,
    scene_source: str,
    scene_model: Path | None,
) -> list[str]:
    command = [
        str(Path(args.maniskill_python).expanduser()),
        "-m",
        "maniskill_curobo.scripts.execute_curobo_pick",
        "--env-id",
        args.env_id,
        "--zerograsp-output",
        str(zg_output_dir),
        "--seed",
        str(seed),
        "--camera",
        args.camera,
        "--width",
        str(args.width),
        "--height",
        str(args.height),
        "--mask-mode",
        args.mask_mode,
        "--camera-eye",
        *[str(float(value)) for value in args.camera_eye],
        "--camera-target",
        *[str(float(value)) for value in args.camera_target],
        "--render-width",
        str(args.render_width),
        "--render-height",
        str(args.render_height),
        "--approach-axis",
        args.approach_axis,
        "--pregrasp-offset",
        str(args.pregrasp_offset),
        "--lift-offset",
        str(args.lift_offset),
        "--workspace-z-min",
        str(args.workspace_z_min),
        "--grasp-depth-scale",
        str(args.grasp_depth_scale),
        "--grasp-depth-max-offset",
        str(args.grasp_depth_max_offset),
        "--candidate-top-k",
        str(args.candidate_top_k),
        "--close-steps",
        str(args.close_steps),
        "--settle-steps",
        str(args.settle_steps),
        "--settle-before-export-steps",
        str(args.settle_before_export_steps),
        "--action-repeat",
        str(args.action_repeat),
        "--max-waypoints-per-stage",
        str(args.max_waypoints_per_stage),
        "--robot-config",
        args.robot_config,
        "--scene-source",
        scene_source,
        "--scene-min-cuboid-dimension",
        str(args.scene_min_cuboid_dimension),
        "--warmup-iterations",
        str(args.warmup_iterations),
        "--video-fps",
        str(args.video_fps),
        "--video-out",
        str(run_dir / "execution.mp4"),
        "--output-dir",
        str(run_dir),
        "--no-grasp-marker",
    ]
    if scene_model is not None:
        command.extend(["--scene-model", str(scene_model)])
    if args.grasp_depth_auto_fallback:
        command.append("--grasp-depth-auto-fallback")
    if not args.record_video:
        command.append("--no-video")
    return command


def raw_segmentation(obs: dict[str, Any], camera_name: str):
    sensor = obs["sensor_data"][camera_name]
    value = sensor["PositionSegmentation"]
    if hasattr(value, "detach"):
        arr = value.detach().cpu().numpy()
    else:
        import numpy as np

        arr = np.asarray(value)
    return arr[0, :, :, 3].astype("int32")


class NonClosingEnvProxy:
    """Delegate to a Gym environment while keeping it alive between episodes."""

    def __init__(self, env: Any):
        object.__setattr__(self, "_env", env)

    def __getattr__(self, name: str) -> Any:
        return getattr(self._env, name)

    def __setattr__(self, name: str, value: Any) -> None:
        setattr(self._env, name, value)

    def close(self) -> None:
        return None


class PersistentRealExecutionRunner:
    """Run execute_curobo_pick in-process with cached ManiSkill resources.

    M3 uses per-seed fixed scene files, so the cuRobo planner is rebuilt when
    the scene signature changes. The optimization here avoids repeatedly
    launching Python and rebuilding the ManiSkill renderer/camera stack.
    """

    def __init__(
        self,
        *,
        repo_root: Path,
        execute_module: Any | None = None,
    ):
        if execute_module is None:
            from maniskill_curobo.scripts import execute_curobo_pick as execute_module

        self.repo_root = Path(repo_root).resolve()
        self.execute_module = execute_module
        self._original_build_env: Callable[..., Any] = execute_module.build_env
        self._original_build_planner: Callable[..., Any] = execute_module.build_planner
        self._env: Any | None = None
        self._env_proxy: NonClosingEnvProxy | None = None
        self._env_signature: tuple[Any, ...] | None = None
        self._planner: Any | None = None
        self._scene_signature: str | None = None
        self._scene_family: str | None = None
        self._episode_count = 0
        self._planner_rebuild_count = 0
        self._last_planner_reused = False
        execute_module.build_env = self._build_env
        execute_module.build_planner = self._build_planner

    def _build_env(self, args: argparse.Namespace) -> NonClosingEnvProxy:
        signature = environment_signature(args)
        if self._env is None:
            self._env = build_real_benchmark_env(args)
            self._env_proxy = NonClosingEnvProxy(self._env)
            self._env_signature = signature
        elif signature != self._env_signature:
            raise RuntimeError(
                "Persistent M3 worker environment configuration changed: "
                f"expected={self._env_signature}, received={signature}"
            )
        assert self._env_proxy is not None
        return self._env_proxy

    def acquire_env(self, args: argparse.Namespace) -> NonClosingEnvProxy:
        """Return the same persistent env used by execute_curobo_pick."""

        return self._build_env(args)

    def _build_planner(
        self,
        args: argparse.Namespace,
        scene_model: Any = None,
    ) -> Any:
        signature = scene_model_signature(scene_model)
        planner_scene_model = load_planner_scene_model(scene_model)
        family = planner_scene_family(planner_scene_model)
        if self._planner is not None and signature == self._scene_signature:
            reset_seed = getattr(self._planner, "reset_seed", None)
            if callable(reset_seed):
                reset_seed()
            self._last_planner_reused = True
            return self._planner
        if self._planner is not None and family == self._scene_family:
            self._planner.clear_scene_cache()
            self._planner.update_world(planner_scene_model)
            reset_seed = getattr(self._planner, "reset_seed", None)
            if callable(reset_seed):
                reset_seed()
            self._scene_signature = signature
            self._last_planner_reused = True
            return self._planner

        self._destroy_planner()
        self._planner = build_cached_planner(args, planner_scene_model)
        self._scene_signature = signature
        self._scene_family = family
        self._planner_rebuild_count += 1
        self._last_planner_reused = False
        return self._planner

    def _destroy_planner(self) -> None:
        if self._planner is None:
            return
        destroy = getattr(self._planner, "destroy", None)
        if callable(destroy):
            destroy()
        self._planner = None
        self._scene_signature = None
        self._scene_family = None
        gc.collect()
        try:
            import torch

            if torch.cuda.is_available():
                torch.cuda.empty_cache()
        except Exception:
            pass

    def run(
        self,
        command: list[str],
        *,
        logs_dir: Path,
        name: str,
    ) -> dict[str, Any]:
        logs_dir.mkdir(parents=True, exist_ok=True)
        stdout_path = logs_dir / f"{name}.stdout.log"
        stderr_path = logs_dir / f"{name}.stderr.log"
        command_path = logs_dir / f"{name}.command.sh"
        command_path.write_text(
            "PYTHONPATH=. " + shlex.join(command) + "\n",
            encoding="utf-8",
        )
        argv = in_process_execute_argv(command)
        env_was_initialized = self._env is not None
        rebuild_count_before = self._planner_rebuild_count
        started = time.time()
        exit_code = 0
        with stdout_path.open("w", encoding="utf-8") as stdout, stderr_path.open(
            "w", encoding="utf-8"
        ) as stderr:
            try:
                with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                    result = self.execute_module.main(argv)
                exit_code = int(result or 0)
            except Exception:
                exit_code = 1
                traceback.print_exc(file=stderr)
        self._episode_count += 1
        return {
            "exit_code": exit_code,
            "runtime_sec": float(time.time() - started),
            "stdout_log": str(stdout_path),
            "stderr_log": str(stderr_path),
            "command_path": str(command_path),
            "persistent_execution": True,
            "episode_index": self._episode_count,
            "environment_reused": env_was_initialized,
            "planner_reused": bool(self._last_planner_reused),
            "planner_rebuilt": self._planner_rebuild_count > rebuild_count_before,
            "planner_rebuild_count": int(self._planner_rebuild_count),
        }

    def close(self) -> None:
        self.execute_module.build_env = self._original_build_env
        self.execute_module.build_planner = self._original_build_planner
        self._destroy_planner()
        if self._env is not None:
            self._env.close()
            self._env = None
            self._env_proxy = None
            self._env_signature = None


def environment_signature(args: argparse.Namespace) -> tuple[Any, ...]:
    return (
        str(args.env_id),
        str(args.camera),
        int(args.width),
        int(args.height),
        int(args.render_width),
        int(args.render_height),
        tuple(float(value) for value in args.camera_eye),
        tuple(float(value) for value in args.camera_target),
    )


def build_real_benchmark_env(args: argparse.Namespace) -> Any:
    """Build a sensor env without mixing minimal and default shader formats."""

    import gymnasium as gym
    import mani_skill.envs  # noqa: F401
    from mani_skill.render import PREBUILT_SHADER_CONFIGS, set_shader_pack
    from mani_skill.utils import sapien_utils

    # Importing the execution stack can leave SAPIEN's global picture formats
    # on the default shader while the sensor config says minimal. Reset both
    # the shader directory and integer PositionSegmentation format explicitly.
    set_shader_pack(PREBUILT_SHADER_CONFIGS["minimal"])
    sensor_configs: dict[str, Any] = {
        "width": args.width,
        "height": args.height,
        "shader_pack": "minimal",
        args.camera: {
            "pose": sapien_utils.look_at(list(args.camera_eye), list(args.camera_target)),
            "shader_pack": "minimal",
        },
    }
    return gym.make(
        args.env_id,
        render_mode="rgb_array",
        control_mode="pd_joint_pos",
        robot_uids="panda",
        obs_mode="sensor_data",
        max_episode_steps=1000,
        sensor_configs=sensor_configs,
        human_render_camera_configs={
            "width": args.render_width,
            "height": args.render_height,
            "shader_pack": "minimal",
        },
    )


def scene_model_signature(scene_model: Any) -> str:
    if isinstance(scene_model, dict):
        return json.dumps(scene_model, sort_keys=True)
    if scene_model is None:
        return "none"
    path = Path(scene_model).expanduser()
    if path.is_file():
        if path.suffix == ".npz":
            stat = path.stat()
            return f"{path.resolve()}:{stat.st_size}:{stat.st_mtime_ns}"
        return path.read_text(encoding="utf-8").strip()
    return str(scene_model)


def load_planner_scene_model(scene_model: Any) -> Any:
    if scene_model is None or isinstance(scene_model, dict):
        return scene_model
    path = Path(scene_model).expanduser()
    if path.is_file() and path.suffix in {".yml", ".yaml", ".json"}:
        from curobo.scene import Scene

        return Scene.create(json.loads(path.read_text(encoding="utf-8")))
    if path.suffix != ".npz":
        return scene_model

    import numpy as np
    import torch
    from curobo.scene import Cuboid, Scene, VoxelGrid

    with np.load(path) as payload:
        feature = torch.as_tensor(
            payload["feature_tensor"],
            dtype=torch.float16,
            device="cuda:0",
        )
        table = Cuboid(
            name="real_table_static",
            pose=payload["table_pose"].astype(float).tolist(),
            dims=payload["table_dims"].astype(float).tolist(),
        )
        voxel = VoxelGrid(
            name="m4c_workspace_esdf",
            pose=[
                *payload["voxel_center"].astype(float).tolist(),
                1.0,
                0.0,
                0.0,
                0.0,
            ],
            dims=payload["voxel_dims"].astype(float).tolist(),
            voxel_size=float(payload["voxel_size"]),
            feature_tensor=feature,
            feature_dtype=torch.float16,
        )
    return Scene(cuboid=[table], voxel=[voxel])


def planner_scene_family(scene_model: Any) -> str:
    if scene_model is None:
        return "none"
    if isinstance(scene_model, (str, Path, dict)):
        return "serialized"
    if getattr(scene_model, "voxel", None):
        return "voxel"
    if getattr(scene_model, "mesh", None):
        return "mesh"
    return "cuboid"


def build_cached_planner(args: argparse.Namespace, scene_model: Any) -> Any:
    from curobo.motion_planner import MotionPlanner, MotionPlannerCfg

    collision_cache: dict[str, Any] = {"cuboid": 64}
    if getattr(scene_model, "mesh", None):
        collision_cache["mesh"] = 64
    if getattr(scene_model, "voxel", None):
        voxel = scene_model.voxel[0]
        collision_cache["voxel"] = {
            "layers": 1,
            "dims": list(voxel.dims),
            "voxel_size": float(voxel.voxel_size),
        }
    config = MotionPlannerCfg.create(
        robot=args.robot_config,
        scene_model=scene_model,
        collision_cache=collision_cache,
    )
    planner = MotionPlanner(config)
    planner.warmup(
        enable_graph=True,
        num_warmup_iterations=args.warmup_iterations,
    )
    print(f"curobo_scene_model={scene_model}")
    print(f"curobo_joint_names={planner.joint_names}")
    print(f"curobo_tool_frames={planner.tool_frames}")
    return planner


def in_process_execute_argv(command: list[str]) -> list[str]:
    if len(command) < 3 or command[1:3] != [
        "-m",
        "maniskill_curobo.scripts.execute_curobo_pick",
    ]:
        raise ValueError(f"Unsupported persistent execution command: {command}")
    return command[3:]


def run_command(
    command: list[str],
    *,
    cwd: Path,
    logs_dir: Path,
    name: str,
) -> dict[str, Any]:
    logs_dir.mkdir(parents=True, exist_ok=True)
    stdout_path = logs_dir / f"{name}.stdout.log"
    stderr_path = logs_dir / f"{name}.stderr.log"
    command_path = logs_dir / f"{name}.command.sh"
    command_path.write_text("PYTHONPATH=. " + shlex.join(command) + "\n", encoding="utf-8")
    started = time.time()
    with stdout_path.open("w", encoding="utf-8") as stdout, stderr_path.open(
        "w", encoding="utf-8"
    ) as stderr:
        proc = subprocess.run(
            command,
            cwd=str(cwd),
            stdout=stdout,
            stderr=stderr,
            text=True,
            env=env_with_pythonpath(),
        )
    return {
        "exit_code": int(proc.returncode),
        "runtime_sec": float(time.time() - started),
        "stdout_log": str(stdout_path),
        "stderr_log": str(stderr_path),
        "command_path": str(command_path),
    }


def summarize_run(
    *,
    stage: str,
    seed: int,
    run_dir: Path,
    command: dict[str, Any] | None = None,
    reused: bool = False,
) -> dict[str, Any]:
    manifest_path = run_dir / "run_manifest.json"
    if not manifest_path.is_file():
        return {
            "stage": stage,
            "seed": seed,
            "status": "missing_run_manifest",
            "outcome": "missing_run_manifest",
            "object_lift_success": False,
            "run_dir": str(run_dir),
            "command": command,
            "reused": reused,
        }
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    metrics = manifest.get("object_lift_metrics") or {}
    grasp = manifest.get("grasp") or {}
    return {
        "stage": stage,
        "seed": seed,
        "status": "complete",
        "outcome": manifest_outcome(manifest),
        "object_lift_success": bool(metrics.get("object_lift_success")),
        "height_delta_m": metrics.get("height_delta_m"),
        "max_height_delta_m": metrics.get("max_height_delta_m"),
        "final_object_tcp_distance_m": metrics.get("final_object_tcp_distance_m"),
        "failure_reason": manifest.get("failure_reason")
        or metrics.get("failure_reason")
        or "",
        "depth_m": grasp.get("depth_m"),
        "depth_offset": grasp.get("grasp_depth_offset"),
        "candidate_selection": grasp.get("candidate_selection"),
        "curobo_scene": manifest.get("curobo_scene"),
        "run_dir": str(run_dir),
        "manifest_path": str(manifest_path),
        "video_path": manifest.get("video_saved"),
        "command": command,
        "reused": reused,
    }


def manifest_outcome(manifest: dict[str, Any]) -> str:
    metrics = manifest.get("object_lift_metrics") or {}
    if metrics.get("object_lift_success"):
        return "success"
    reason = str(manifest.get("failure_reason") or "")
    if "candidate selection failed" in reason:
        return "planning_failed_candidate_selection"
    if "stage=pre" in reason:
        return "planning_failed_pre"
    if "stage=grasp" in reason:
        return "planning_failed_grasp"
    if "stage=lift" in reason:
        return "planning_failed_lift"
    if reason:
        return "execution_failed"
    return str(metrics.get("failure_reason") or "failed")


def find_candidate_output(candidate_root: Path, seed: int) -> Path | None:
    candidates = [
        candidate_root / f"seed{seed:03d}" / "setup" / "zg_output",
        candidate_root / f"seed{seed:03d}_base" / "zg_output",
        candidate_root / f"seed{seed:03d}" / "zg_output",
        candidate_root / f"seed{seed:03d}" / "baseline" / "zg_output",
        candidate_root / f"seed{seed:03d}" / "depth" / "zg_output",
        candidate_root / f"seed{seed:03d}" / "corrected_depth" / "zg_output",
    ]
    for path in candidates:
        if (path / "recommended_grasp_top1.json").is_file():
            return path
    return None


def find_reconstruction_dirs(
    reconstruction_root: Path,
    seed: int,
) -> tuple[Path, Path] | None:
    candidates = [
        reconstruction_root / f"seed{seed:03d}" / "setup",
        reconstruction_root / f"seed{seed:03d}",
    ]
    for setup_dir in candidates:
        input_dir = setup_dir / "zg_input"
        output_dir = setup_dir / "zg_output"
        if (
            (input_dir / "camera.json").is_file()
            and (input_dir / "rgbd.npz").is_file()
            and (output_dir / "run_report.json").is_file()
            and list((output_dir / "raw_outputs").glob("*.reconstruction.npz"))
        ):
            return input_dir, output_dir
    return None


def load_existing_records(output_root: Path) -> dict[str, dict[int, dict[str, Any]]]:
    path = output_root / "records.jsonl"
    records: dict[str, dict[int, dict[str, Any]]] = {}
    if not path.is_file():
        return records
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        record = json.loads(line)
        records.setdefault(str(record["stage"]), {})[int(record["seed"])] = record
    return records


def write_results(
    output_root: Path,
    args: argparse.Namespace,
    seeds: list[int],
    records_by_stage: dict[str, dict[int, dict[str, Any]]],
) -> dict[str, Any]:
    ordered_records: list[dict[str, Any]] = []
    counts: dict[str, Any] = {}
    labels = stage_labels_for(args)
    for stage in args.stages:
        stage_records = [records_by_stage.get(stage, {}).get(seed) for seed in seeds]
        stage_records = [record for record in stage_records if record is not None]
        complete = [record for record in stage_records if record.get("status") == "complete"]
        counts[stage] = {
            "label": labels[stage],
            "processed": len(stage_records),
            "complete": len(complete),
            "successes": sum(bool(record.get("object_lift_success")) for record in complete),
            "outcomes": outcome_counts(complete),
        }
        ordered_records.extend(stage_records)

    summary = {
        "env_id": args.env_id,
        "seed_start": args.seed_start,
        "seed_end": args.seed_end,
        "stages": args.stages,
        "stage_labels": labels,
        "point_cloud_source": args.point_cloud_source,
        "zerograsp_reconstruction_root": args.zerograsp_reconstruction_root,
        "grasp_depth_scale": args.grasp_depth_scale,
        "grasp_depth_auto_fallback": bool(args.grasp_depth_auto_fallback),
        "candidate_top_k": int(args.candidate_top_k),
        "record_video": bool(args.record_video),
        "reuse_candidate_root": args.reuse_candidate_root,
        "counts": counts,
    }
    write_json_atomic(output_root / "summary.json", summary)
    progress = {
        "processed_records": len(ordered_records),
        "requested_records": len(args.stages) * len(seeds),
        "counts": counts,
    }
    write_json_atomic(output_root / "progress.json", progress)
    temp = output_root / "records.jsonl.tmp"
    with temp.open("w", encoding="utf-8") as file:
        for record in ordered_records:
            file.write(json.dumps(record, ensure_ascii=False) + "\n")
    temp.replace(output_root / "records.jsonl")
    write_markdown_summary(output_root / "summary.md", summary)
    return summary


def outcome_counts(records: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for record in records:
        outcome = str(record.get("outcome"))
        counts[outcome] = counts.get(outcome, 0) + 1
    return counts


def write_markdown_summary(path: Path, summary: dict[str, Any]) -> None:
    lines = [
        "# cuRobo Real Collision World M0-M4 Summary",
        "",
        f"- env_id: `{summary['env_id']}`",
        f"- seeds: `{summary['seed_start']}-{summary['seed_end']}`",
        f"- candidate_top_k: `{summary['candidate_top_k']}`",
        f"- grasp_depth_scale: `{summary['grasp_depth_scale']}`",
        f"- grasp_depth_auto_fallback: `{summary['grasp_depth_auto_fallback']}`",
        "",
        "| Stage | Label | Processed | Complete | Lift Success | Outcomes |",
        "|---|---|---:|---:|---:|---|",
    ]
    for stage, counts in summary["counts"].items():
        outcomes = ", ".join(
            f"{key}: {value}" for key, value in sorted(counts["outcomes"].items())
        )
        lines.append(
            f"| `{stage}` | {counts['label']} | {counts['processed']} | "
            f"{counts['complete']} | {counts['successes']} | {outcomes} |"
        )
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_json_atomic(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_suffix(path.suffix + ".tmp")
    temp.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    temp.replace(path)


def env_with_pythonpath() -> dict[str, str]:
    env = os.environ.copy()
    existing = env.get("PYTHONPATH")
    root = str(Path(__file__).resolve().parents[1])
    env["PYTHONPATH"] = root if not existing else f"{root}:{existing}"
    return env


if __name__ == "__main__":
    raise SystemExit(main())
