robot_cfg:
  kinematics:
    format_version: 2.0
    urdf_path: /home/openclaw-server/projects/zerograsp/maniskill_curobo_fangzhou/generated/lift2_maniskill_visual.urdf
    asset_root_path: /home/openclaw-server/projects/zerograsp/maniskill_curobo_fangzhou/urdf/lift2
    base_link: base_link
    tool_frames:
    - right_tcp
    grasp_contact_link_names:
    - right_link26
    - right_link27
    - right_link28
    - attached_object
    collision_link_names: &id001
    - right_link21
    - right_link22
    - right_link23
    - right_link24
    - right_link25
    - right_link26
    - right_link27
    - right_link28
    collision_sphere_buffer: 0.0
    collision_spheres:
      right_link21:
      - center:
        - 0.0078
        - 0.0
        - 0.0288
        radius: 0.058
      right_link22:
      - center:
        - -0.008
        - 0.0
        - 0.0007
        radius: 0.035
      - center:
        - -0.0451429
        - 0.0
        - 0.0007
        radius: 0.035
      - center:
        - -0.0822857
        - 0.0
        - 0.0007
        radius: 0.035
      - center:
        - -0.1194286
        - 0.0
        - 0.0007
        radius: 0.035
      - center:
        - -0.1565714
        - 0.0
        - 0.0007
        radius: 0.035
      - center:
        - -0.1937143
        - 0.0
        - 0.0007
        radius: 0.035
      - center:
        - -0.2308571
        - 0.0
        - 0.0007
        radius: 0.035
      - center:
        - -0.268
        - 0.0
        - 0.0007
        radius: 0.035
      right_link23:
      - center:
        - 0.01
        - 0.0
        - 0.042
        radius: 0.04
      - center:
        - 0.045
        - 0.0
        - 0.0445714
        radius: 0.04
      - center:
        - 0.08
        - 0.0
        - 0.0471429
        radius: 0.04
      - center:
        - 0.115
        - 0.0
        - 0.0497143
        radius: 0.04
      - center:
        - 0.15
        - 0.0
        - 0.0522857
        radius: 0.04
      - center:
        - 0.185
        - 0.0
        - 0.0548571
        radius: 0.04
      - center:
        - 0.22
        - 0.0
        - 0.0574286
        radius: 0.04
      - center:
        - 0.255
        - 0.0
        - 0.06
        radius: 0.04
      - center:
        - 0.004
        - -0.036
        - 0.006
        radius: 0.022
      - center:
        - 0.01
        - 0.036
        - 0.02
        radius: 0.025
      right_link24:
      - center:
        - 0.005
        - 0.0
        - 0.004
        radius: 0.034
      - center:
        - 0.02525
        - 0.0
        - 0.022
        radius: 0.034
      - center:
        - 0.0455
        - 0.0
        - 0.04
        radius: 0.034
      - center:
        - 0.06575
        - 0.0
        - 0.058
        radius: 0.034
      - center:
        - 0.086
        - 0.0
        - 0.076
        radius: 0.034
      right_link25:
      - center:
        - 0.0
        - 0.0
        - -0.015
        radius: 0.031
      - center:
        - 0.0
        - 0.0
        - -0.0352
        radius: 0.031
      - center:
        - 0.0
        - 0.0
        - -0.0554
        radius: 0.031
      - center:
        - 0.0
        - 0.0
        - -0.0756
        radius: 0.031
      - center:
        - 0.0
        - 0.0
        - -0.0958
        radius: 0.031
      - center:
        - 0.0
        - 0.0
        - -0.116
        radius: 0.031
      right_link26:
      - center:
        - 0.038
        - -0.022
        - -0.002
        radius: 0.029
      - center:
        - 0.038
        - 0.0
        - -0.002
        radius: 0.029
      - center:
        - 0.038
        - 0.022
        - -0.002
        radius: 0.029
      - center:
        - 0.014
        - -0.03
        - -0.004
        radius: 0.018
      - center:
        - 0.039
        - -0.03
        - -0.004
        radius: 0.018
      - center:
        - 0.064
        - -0.03
        - -0.004
        radius: 0.018
      - center:
        - 0.014
        - 0.03
        - -0.004
        radius: 0.018
      - center:
        - 0.039
        - 0.03
        - -0.004
        radius: 0.018
      - center:
        - 0.064
        - 0.03
        - -0.004
        radius: 0.018
      - center:
        - 0.04
        - 0.002
        - 0.019
        radius: 0.006
      - center:
        - 0.036
        - 0.0
        - -0.064
        radius: 0.023
      - center:
        - 0.035
        - 0.0
        - -0.0955
        radius: 0.021
      - center:
        - 0.034
        - 0.0
        - -0.127
        radius: 0.02
      right_link27:
      - center:
        - 0.058
        - -0.006
        - 0.02
        radius: 0.018
      - center:
        - 0.034
        - -0.012
        - 0.012
        radius: 0.018
      - center:
        - 0.046
        - -0.01
        - 0.01
        radius: 0.02
      - center:
        - 0.028
        - -0.014
        - 0.0075
        radius: 0.02
      - center:
        - 0.01
        - -0.018
        - 0.005
        radius: 0.02
      - center:
        - 0.005
        - -0.016
        - -0.018
        radius: 0.02
      - center:
        - -0.002
        - -0.0145
        - -0.0355
        radius: 0.02
      - center:
        - -0.009
        - -0.013
        - -0.053
        radius: 0.02
      - center:
        - -0.017
        - -0.044
        - 0.018
        radius: 0.012
      - center:
        - -0.017
        - -0.066
        - 0.031
        radius: 0.012
      right_link28:
      - center:
        - 0.058
        - 0.006
        - 0.01
        radius: 0.018
      - center:
        - 0.034
        - 0.012
        - 0.002
        radius: 0.018
      - center:
        - 0.046
        - 0.01
        - 0.002
        radius: 0.02
      - center:
        - 0.028
        - 0.0155
        - -0.0025
        radius: 0.02
      - center:
        - 0.01
        - 0.021
        - -0.007
        radius: 0.02
      - center:
        - 0.004
        - 0.016
        - -0.028
        radius: 0.02
      - center:
        - -0.001
        - 0.014
        - -0.0405
        radius: 0.02
      - center:
        - -0.006
        - 0.012
        - -0.053
        radius: 0.02
      - center:
        - -0.018
        - 0.044
        - -0.018
        radius: 0.01
      - center:
        - -0.019
        - 0.066
        - -0.021
        radius: 0.01
    extra_collision_spheres:
      attached_object: 4
    extra_links:
      right_tcp:
        parent_link_name: right_link26
        link_name: right_tcp
        joint_name: right_tcp_fixed_joint
        joint_type: FIXED
        fixed_transform:
        - 0.14496999979019165
        - 0.0017859999788925052
        - 0.0
        - 1.0
        - 0.0
        - 0.0
        - 0.0
      attached_object:
        parent_link_name: right_tcp
        link_name: attached_object
        joint_name: right_attach_joint
        joint_type: FIXED
        fixed_transform:
        - 0.0
        - 0.0
        - 0.0
        - 1.0
        - 0.0
        - 0.0
        - 0.0
    lock_joints:
      right_joint27: 0.029999999329447746
      right_joint28: 0.029999999329447746
      joint4: 0.46
    mesh_link_names: *id001
    self_collision_buffer:
      right_link21: 0.0
      right_link22: 0.0
      right_link23: 0.0
      right_link24: 0.0
      right_link25: 0.0
      right_link26: 0.0
      right_link27: 0.0
      right_link28: 0.0
      attached_object: 0.0
    self_collision_ignore:
      right_link21:
      - right_link22
      right_link22:
      - right_link23
      right_link23:
      - right_link24
      - right_link25
      right_link24:
      - right_link25
      - right_link26
      right_link25:
      - right_link26
      - right_link27
      - right_link28
      right_link26:
      - right_link27
      - right_link28
      - right_tcp
      - attached_object
      right_link27:
      - right_link28
      - right_tcp
      - attached_object
      right_link28:
      - right_tcp
      - attached_object
      right_tcp:
      - attached_object
    cspace:
      joint_names:
      - right_joint21
      - right_joint22
      - right_joint23
      - right_joint24
      - right_joint25
      - right_joint26
      default_joint_position:
      - 0.0
      - 1.2000000476837158
      - 1.7999999523162842
      - 0.0
      - 0.0
      - 0.0
      null_space_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      cspace_distance_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      position_limit_clip: 0.01
      max_acceleration: 8.0
      max_jerk: 500.0
    use_global_cumul: true
